/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.CursoCtrl;
import Controlador.DiplomaCtrl;
import Controlador.UsuarioCtrl;
import Modelo.Curso;
import Modelo.Pregunta;
import Modelo.Usuario;
import Modelo.UsuarioCurso;
import Utilitarios.Imagenes;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import static java.awt.Component.TOP_ALIGNMENT;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.border.LineBorder;

/**
 *
 * @author Jekse
 */
public class CursosPersona extends javax.swing.JPanel {
    private final Principal p;
    private final CursoCtrl curCt;
    private GridBagConstraints gbc=new GridBagConstraints();
    private final DiplomaCtrl dipCt;
    private final Imagenes imgs=new Imagenes();
    public int cod=0;
    public int codcur=0;
    
    /**
     * Creates new form CursosPersona
     * @param p   
     * @param usuCt   
     * @param curCt 
     */
    public CursosPersona(Principal p,UsuarioCtrl usuCt,CursoCtrl curCt) {
        initComponents();
        this.p=p;
        this.curCt=curCt;
        dipCt=new DiplomaCtrl(usuCt,curCt);
        jscPanel.setBorder(new LineBorder(Color.BLACK));
        jscPanel.getVerticalScrollBar().setUnitIncrement(15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscPanel = new javax.swing.JScrollPane();
        jpMisCursos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jscPanel.setPreferredSize(new java.awt.Dimension(1000, 650));

        jpMisCursos.setBackground(new java.awt.Color(255, 255, 255));
        jpMisCursos.setLayout(new java.awt.GridBagLayout());
        jscPanel.setViewportView(jpMisCursos);

        add(jscPanel);
        jscPanel.setBounds(0, 87, 1000, 563);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MIS CURSOS");
        add(jLabel2);
        jLabel2.setBounds(10, 10, 154, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DESCRIPCION");
        add(jLabel4);
        jLabel4.setBounds(400, 50, 131, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("COSTO");
        add(jLabel3);
        jLabel3.setBounds(890, 60, 62, 22);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras);
        btnAtras.setBounds(910, 10, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        p.visualizarVentanas(false,false,false,false,true,false,false,true,false,false);
        p.cambiarVentanas(4);   
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpMisCursos;
    private javax.swing.JScrollPane jscPanel;
    // End of variables declaration//GEN-END:variables

    public void cargarCursos(){
        ArrayList<UsuarioCurso> lista1;
        ArrayList<Curso> lista2;
        jscPanel.getVerticalScrollBar().setValue(0);        
        jpMisCursos.removeAll();       
        lista1=curCt.cursosPersona(cod);
        lista2=curCt.cursos();        
        ImageIcon img;        
        gbc.weightx=0.25;        
        if(lista1!=null && !(lista1.isEmpty())){
            for(int i=0;i<lista1.size();i++){
                for(int j=0;j<lista2.size();j++){
                    if(lista1.get(i).getCodCurso()==lista2.get(j).getCodigoCurso()){
                        final int codcur=lista1.get(i).getCodCurso();
                        img=new ImageIcon(imgs.buscarImg(lista2.get(j).getFotoCurso()));
                        Icon icon=new ImageIcon(img.getImage().getScaledInstance(190,170,Image.SCALE_SMOOTH));
                        JLabel lblimg=new JLabel();
                        lblimg.setBorder(new LineBorder(Color.BLACK));
                        lblimg.setHorizontalAlignment((int)CENTER_ALIGNMENT);
                        lblimg.setIcon(icon);
                        JTextArea desc=new JTextArea();
                        desc.setBorder(new LineBorder(Color.BLACK));
                        desc.setAlignmentX(TOP_ALIGNMENT);
                        desc.setFont(new Font("Calibri", Font.PLAIN, 17));
                        desc.setWrapStyleWord(true);
                        desc.setLineWrap(true);
                        desc.setEditable(false);               
                        desc.setText("Nombre: "+lista2.get(j).getNombreCurso()+"\n"+
                             "Descripcion: "+lista2.get(j).getDescripcion());
                        JLabel valor=new JLabel();
                        valor.setBorder(new LineBorder(Color.BLACK));
                        valor.setHorizontalAlignment((int)CENTER_ALIGNMENT);
                        valor.setFont(new Font("Calibri", Font.BOLD, 17));
                        valor.setText(String.valueOf("$"+lista2.get(j).getValorCurso()));
                        JButton boton=new JButton("Certificar");
                        boton.addActionListener((ActionEvent e) -> {
                            dipCt.cargarRespuestas();
                            dipCt.cargarPreguntas();
                            solicitarCertificado(codcur);
                        });
                        gbc.fill=GridBagConstraints.BOTH;
                        gbc.gridx=0;
                        gbc.gridy=j;
                        gbc.ipadx=0;
                        gbc.ipady=0;
                        jpMisCursos.add(lblimg,gbc);
                        gbc.gridx=1;
                        gbc.ipadx=0;
                        gbc.ipady=0;                
                        jpMisCursos.add(desc,gbc);
                        gbc.gridx=2;                
                        jpMisCursos.add(valor,gbc);
                        gbc.fill=GridBagConstraints.BASELINE;
                        gbc.gridx=3;
                        gbc.ipadx=20;
                        gbc.ipady=30;
                        jpMisCursos.add(boton,gbc);
                        jpMisCursos.updateUI();
                    }                
                }
            }
        }                    
    }

    private void solicitarCertificado(int codcurso) {
        
        JFrame emergente = new JFrame();        
        emergente.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        emergente.setResizable(false);
        JDialog jd = new JDialog(emergente);                        
        jd.setLayout(new GridLayout(12,1));
        jd.setBounds(500,200,600,400);
        jd.setResizable(false);

        JLabel lblPre1 = new JLabel();
        lblPre1.setText(dipCt.preguntasCurso(codcurso).get(0).getPregunta());
        JTextField txtPre1=new JTextField();            
        JLabel lblPre2 = new JLabel();
        lblPre2.setText(dipCt.preguntasCurso(codcurso).get(1).getPregunta());
        JTextField txtPre2=new JTextField();
        JLabel lblPre3 = new JLabel();
        lblPre3.setText(dipCt.preguntasCurso(codcurso).get(2).getPregunta());
        JTextField txtPre3=new JTextField();
        JLabel lblPre4 = new JLabel();
        lblPre4.setText(dipCt.preguntasCurso(codcurso).get(3).getPregunta());
        JTextField txtPre4=new JTextField();
        JLabel lblPre5 = new JLabel();
        lblPre5.setText(dipCt.preguntasCurso(codcurso).get(4).getPregunta());
        JTextField txtPre5=new JTextField();
        JButton btnGuardar = new JButton("Guardar");
        JButton btnCerrar = new JButton("Cerrar");
        btnGuardar.addActionListener((ActionEvent e) -> {
            if(!txtPre1.getText().equals("") &&
               !txtPre2.getText().equals("")&&
               !txtPre3.getText().equals("") &&
               !txtPre4.getText().equals("") &&
               !txtPre5.getText().equals(""))
            {
                ArrayList<Pregunta> respuestas=new ArrayList<>();
                int cedu=cod;
                Pregunta resp;
                resp=new Pregunta(codcurso,dipCt.preguntasCurso(codcurso).get(0).getPregunta());
                resp.setCedula(cedu);
                resp.setRespuesta(txtPre1.getText());
                respuestas.add(resp);
                resp=new Pregunta(codcurso,dipCt.preguntasCurso(codcurso).get(1).getPregunta());
                resp.setCedula(cedu);
                resp.setRespuesta(txtPre2.getText());
                respuestas.add(resp);
                resp=new Pregunta(codcurso,dipCt.preguntasCurso(codcurso).get(2).getPregunta());
                resp.setCedula(cedu);
                resp.setRespuesta(txtPre3.getText());
                respuestas.add(resp);
                resp=new Pregunta(codcurso,dipCt.preguntasCurso(codcurso).get(3).getPregunta());
                resp.setCedula(cedu);
                resp.setRespuesta(txtPre4.getText());
                respuestas.add(resp);
                resp=new Pregunta(codcurso,dipCt.preguntasCurso(codcurso).get(4).getPregunta());
                resp.setCedula(cedu);
                resp.setRespuesta(txtPre5.getText());
                respuestas.add(resp);
                if(dipCt.responderPreguntas(respuestas)){
                    emergente.dispose();
                    JOptionPane.showMessageDialog(null,"Respuestas guardadas","Alerta",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this,"No se pudo guardar","Alerta",JOptionPane.ERROR_MESSAGE);
                }
                
            }else{
                JOptionPane.showMessageDialog(null,"Rellene los campos","Alerta",JOptionPane.ERROR_MESSAGE);
            }
        });
        btnCerrar.addActionListener((ActionEvent e) -> {
            emergente.dispose();
        });
        jd.add(lblPre1);
        jd.add(txtPre1);
        jd.add(lblPre2);
        jd.add(txtPre2);
        jd.add(lblPre3);
        jd.add(txtPre3);
        jd.add(lblPre4);
        jd.add(txtPre4);
        jd.add(lblPre5);
        jd.add(txtPre5);
        jd.add(btnGuardar);
        jd.add(btnCerrar);
        jd.setVisible(true);
    }
}
        

