/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.CursoCtrl;
import Controlador.DiplomaCtrl;
import Controlador.UsuarioCtrl;
import Modelo.Diploma;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/**
 *
 * @author Jekse
 */
public class Diplomas extends javax.swing.JPanel {
    private Principal p;
    public int cod;
    private CursoCtrl curCtrl;
    private UsuarioCtrl usuCtrl;
    private final DiplomaCtrl dipCt;
    private final DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    /**
     * Creates new form Diplomas
     * @param p
     * @param usuCtrl
     * @param curCtrl
     */
    public Diplomas(Principal p,UsuarioCtrl usuCtrl,CursoCtrl curCtrl) {
        initComponents();
        this.p=p;
        this.curCtrl=curCtrl;
        this.usuCtrl=usuCtrl;
        dipCt=new DiplomaCtrl(usuCtrl,curCtrl);
        jtaDescripcion.setEditable(false);
        jtaDescripcion.setLineWrap(true);
        jtaDescripcion.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDiplomas = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblAdmin1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblCodCurso = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblNombreIns = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNombreEst = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ablaze academy.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(790, 0, 215, 196);

        jtDiplomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtDiplomas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDiplomasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDiplomas);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 60, 740, 180);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("---");
        lblTitulo.setToolTipText("");
        add(lblTitulo);
        lblTitulo.setBounds(290, 260, 310, 30);

        lblAdmin1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin1.setText("MIS DIPLOMAS <3");
        lblAdmin1.setToolTipText("");
        add(lblAdmin1);
        lblAdmin1.setBounds(220, 20, 420, 30);

        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Titulo:");
        lbl1.setToolTipText("");
        add(lbl1);
        lbl1.setBounds(190, 260, 80, 30);

        lbl2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Descripcion:");
        lbl2.setToolTipText("");
        add(lbl2);
        lbl2.setBounds(120, 520, 150, 30);

        lblCodCurso.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCodCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodCurso.setText("---");
        lblCodCurso.setToolTipText("");
        add(lblCodCurso);
        lblCodCurso.setBounds(310, 480, 270, 30);

        lbl3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Nombre Institucion:");
        lbl3.setToolTipText("");
        add(lbl3);
        lbl3.setBounds(50, 300, 220, 30);

        lblNombreIns.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNombreIns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreIns.setText("---");
        lblNombreIns.setToolTipText("");
        add(lblNombreIns);
        lblNombreIns.setBounds(310, 300, 270, 30);

        lbl4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Fecha:");
        lbl4.setToolTipText("");
        add(lbl4);
        lbl4.setBounds(190, 340, 80, 30);

        lbl5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("Nombre Estudiante:");
        lbl5.setToolTipText("");
        add(lbl5);
        lbl5.setBounds(50, 380, 220, 30);

        lbl6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setText("Cedula:");
        lbl6.setToolTipText("");
        add(lbl6);
        lbl6.setBounds(170, 430, 100, 30);

        lbl7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setText("Codigo curso:");
        lbl7.setToolTipText("");
        add(lbl7);
        lbl7.setBounds(110, 480, 160, 30);

        lblFecha.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("---");
        lblFecha.setToolTipText("");
        add(lblFecha);
        lblFecha.setBounds(310, 340, 270, 30);

        lblNombreEst.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNombreEst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreEst.setText("---");
        lblNombreEst.setToolTipText("");
        add(lblNombreEst);
        lblNombreEst.setBounds(310, 380, 270, 30);

        lblCedula.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCedula.setText("---");
        lblCedula.setToolTipText("");
        add(lblCedula);
        lblCedula.setBounds(310, 430, 270, 30);

        btnAtras.setText("atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras);
        btnAtras.setBounds(760, 560, 72, 22);

        jtaDescripcion.setColumns(20);
        jtaDescripcion.setRows(5);
        jScrollPane3.setViewportView(jtaDescripcion);

        add(jScrollPane3);
        jScrollPane3.setBounds(290, 520, 360, 86);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        p.visualizarVentanas(false,false,false,false,true,false,false,false,false,false);
        p.cambiarVentanas(4);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jtDiplomasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDiplomasMouseClicked
        if(dipCt.diplomasPersona(cod)!=null){
            verDiploma();
        }
    }//GEN-LAST:event_jtDiplomasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtDiplomas;
    private javax.swing.JTextArea jtaDescripcion;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lblAdmin1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodCurso;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombreEst;
    private javax.swing.JLabel lblNombreIns;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    
    public void cargarDiplomas(){
        jtDiplomas.setModel(dipCt.tabla(cod));
        jtDiplomas.updateUI();
    }
    
    private void verDiploma(){
        ArrayList<Diploma> lista=dipCt.diplomasPersona(cod);
        int cedula=Integer.parseInt(jtDiplomas.getModel().getValueAt(jtDiplomas.getSelectedRow(),1).toString());
        int codCurso=Integer.parseInt(jtDiplomas.getModel().getValueAt(jtDiplomas.getSelectedRow(),2).toString());
        if(jtDiplomas.getSelectedRow()>=0 && lista!=null && !lista.isEmpty()){
            for(int i=0;i<lista.size();i++){
                if(lista.get(i).getCedula()==cedula && lista.get(i).getCodCurso()==codCurso){
                    lblTitulo.setText(lista.get(i).getTitulo());
                    lblNombreIns.setText(lista.get(i).getNOMBRE_INSTITUCION());
                    lblFecha.setText(dateFormat.format(lista.get(i).getFecha()));
                    lblNombreEst.setText(lista.get(i).getNombreEstudiante());
                    lblCedula.setText(String.valueOf(lista.get(i).getCedula()));
                    lblCodCurso.setText(String.valueOf(lista.get(i).getCodCurso()));
                    jtaDescripcion.setText(lista.get(i).getDescripcion());
                }
            }
        }else{
            lblTitulo.setText("");
            lblNombreIns.setText("");
            lblFecha.setText("");
            lblNombreEst.setText("");
            lblCedula.setText("");
            lblCodCurso.setText("");
            jtaDescripcion.setText("");
        }
    }
}
