/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.UsuarioCtrl;
import Modelo.Usuario;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author juans
 */
public class Ingreso extends javax.swing.JPanel {
    private final Principal p;
    private final Cursos cursos;
    private final Estudiante estudiante;
    private final CursosPersona cursosp;
    private final Diplomas diplo;
    private final UsuarioCtrl usuCt;
    /**
     * Creates new form Ingreso 
     * 
     * @param p
     * @param cursos
     * @param estudiante
     * @param cursosp
     * @param diplo
     * @param usuCt
     */
    public Ingreso(Principal p,UsuarioCtrl usuCt,Cursos cursos,Estudiante estudiante,
                   CursosPersona cursosp,Diplomas diplo)
    
    {       
        initComponents();        
        this.p=p;
        this.cursos=cursos;
        this.estudiante=estudiante;
        this.cursosp=cursosp;
        this.diplo=diplo;
        this.usuCt=usuCt;
        usuAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnIngreso = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        psContraseña = new javax.swing.JPasswordField();

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 650));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ablaze academy.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Bienvenido de nuevo");
        jTextField1.setBorder(null);
        jTextField1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Cédula:");
        jLabel2.setFocusable(false);

        txtCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Contraseña:");
        jLabel1.setFocusable(false);

        btnIngreso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/control-de-accesso.png"))); // NOI18N
        btnIngreso.setToolTipText("Ingresar");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ablaze academy.png"))); // NOI18N
        jLabel4.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psContraseña))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        ingresar();
    }//GEN-LAST:event_btnIngresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPasswordField psContraseña;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables

    private void ingresar() {        
        usuCt.cargarUsuarios();        
        try{            
            switch(usuCt.inicioSesion(Integer.parseInt(txtCedula.getText()),String.valueOf(psContraseña.getPassword()))){               
                case 1->{                    
                    p.habilitar(false,false,false,true,true,false,true);
                    p.visualizarVentanas(false,false,false,false,true,false,false,false,false,false);              
                    estudiante.cod=Integer.parseInt(txtCedula.getText());
                    cursos.cod=Integer.parseInt(txtCedula.getText());
                    cursosp.cod=Integer.parseInt(txtCedula.getText());
                    diplo.cod=Integer.parseInt(txtCedula.getText());
                    limpiarCampos();                    
                    p.cambiarVentanas(4);
                    cursos.inscripcion=true;
                    cursos.atras=true;
                    cursos.ventana=true;
                    JOptionPane.showMessageDialog(this,"Bievenido Estudiante","Bienvenido",JOptionPane.INFORMATION_MESSAGE);                    
                }
                case 2->{                    
                    p.habilitar(false,false,false,false,false,true,false);
                    p.visualizarVentanas(false,false,false,false,false,true,false,false,false,false);
                    limpiarCampos();
                    p.cambiarVentanas(5);
                    cursos.inscripcion=false;
                    cursos.atras=true;
                    cursos.ventana=false;
                    JOptionPane.showMessageDialog(this,"Bievenido de vuelta","DIOS",JOptionPane.INFORMATION_MESSAGE);
                }               
                default->{
                    limpiarCampos();
                    JOptionPane.showMessageDialog(this,"Disculpe los datos no coinciden","Alerta",JOptionPane.ERROR_MESSAGE);
                }                   
            }        
        }catch(HeadlessException | NumberFormatException ex){
            limpiarCampos();
            JOptionPane.showMessageDialog(this,"Revise los datos ingresados","Alerta",JOptionPane.ERROR_MESSAGE);                        
        }        
    }
    
    public void limpiarCampos(){
        psContraseña.setText("");
        txtCedula.setText("");        
    }    

    private void usuAdmin(){
        usuCt.cargarUsuarios();        
        Usuario usu=new Usuario("0000",
                            "Admin",
                            2,
                            9999,
                            1000);        
        usuCt.registrar(usu);             
    }
    
}
    
    
    
    
    

