/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CursoCtrl;
import Controlador.UsuarioCtrl;

/**
 *
 * @author Jekse
 */
public final class  Principal extends javax.swing.JFrame {
    private final UsuarioCtrl usuCt=new UsuarioCtrl();
    private final CursoCtrl curCt=new CursoCtrl();
    private final Inicio inicio=new Inicio(curCt);
    private final Cursos cursos=new Cursos(this,curCt);
    private final Estudiante estu=new Estudiante(this,cursos,usuCt);            
    private final Registro registro=new Registro(usuCt);   
    private final Administrador admin=new Administrador(this,cursos,curCt);        
    private final Diplomas diplomas=new Diplomas(this,usuCt,curCt);
    private final CursosPersona cursosp=new CursosPersona(this,usuCt,curCt);
    private final Ingreso ingreso=new Ingreso(this,usuCt,cursos,estu,cursosp,diplomas);
    private final Cuestionarios cues=new Cuestionarios(this,usuCt,curCt);
    private final Facturas fac=new Facturas(this);
    
    
    /**
     * Creates new form Vista
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        habilitar(true,true,true,false,false,false,false);
        visualizarVentanas(true,false,false,false,false,false,false,false,false,false);
        cambiarVentanas(1);        
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmMenus = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuIngreso = new javax.swing.JMenu();
        menuRegistro = new javax.swing.JMenu();
        menuCursos = new javax.swing.JMenu();
        menuMisCursos = new javax.swing.JMenu();
        menuDiplomas = new javax.swing.JMenu();
        menuCuestionarios = new javax.swing.JMenu();
        menuFacturas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        menuInicio.setBorder(null);
        menuInicio.setText("Inicio");
        menuInicio.setEnabled(false);
        menuInicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicioMouseClicked(evt);
            }
        });
        jmMenus.add(menuInicio);

        menuIngreso.setText("Iniciar Sesion");
        menuIngreso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIngresoMouseClicked(evt);
            }
        });
        jmMenus.add(menuIngreso);

        menuRegistro.setText("Registrarse");
        menuRegistro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistroMouseClicked(evt);
            }
        });
        jmMenus.add(menuRegistro);

        menuCursos.setText("Cursos");
        menuCursos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCursosMouseClicked(evt);
            }
        });
        jmMenus.add(menuCursos);

        menuMisCursos.setText("Mis cursos");
        menuMisCursos.setEnabled(false);
        menuMisCursos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuMisCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMisCursosMouseClicked(evt);
            }
        });
        jmMenus.add(menuMisCursos);

        menuDiplomas.setText("Diplomas");
        menuDiplomas.setEnabled(false);
        menuDiplomas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuDiplomas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDiplomasMouseClicked(evt);
            }
        });
        jmMenus.add(menuDiplomas);

        menuCuestionarios.setText("Cuestionarios");
        menuCuestionarios.setEnabled(false);
        menuCuestionarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuCuestionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCuestionariosMouseClicked(evt);
            }
        });
        jmMenus.add(menuCuestionarios);

        menuFacturas.setText("Facturas");
        menuFacturas.setEnabled(false);
        menuFacturas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFacturasMouseClicked(evt);
            }
        });
        jmMenus.add(menuFacturas);

        setJMenuBar(jmMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicioMouseClicked
        if(menuInicio.isEnabled()){
            habilitar(true,true,true,false,false,false,false);
            visualizarVentanas(true,false,false,false,false,false,false,false,false,false);
            cambiarVentanas(1);
        }
    }//GEN-LAST:event_menuInicioMouseClicked

    private void menuIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIngresoMouseClicked
        if(menuIngreso.isEnabled()){
            habilitar(true,true,true,false,false,false,false);
            visualizarVentanas(false,true,false,false,false,false,false,false,false,false);
            cambiarVentanas(2);
        }
    }//GEN-LAST:event_menuIngresoMouseClicked

    private void menuRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistroMouseClicked
        if(menuRegistro.isEnabled()){
            habilitar(true,true,true,false,false,false,false);
            visualizarVentanas(false,false,true,false,false,false,false,false,false,false);
            cambiarVentanas(3);
        }
    }//GEN-LAST:event_menuRegistroMouseClicked

    private void menuCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCursosMouseClicked
        visualizarVentanas(false,false,false,true,false,false,false,false,false,false);        
        cambiarVentanas(6);
    }//GEN-LAST:event_menuCursosMouseClicked

    private void menuMisCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMisCursosMouseClicked
        if(menuMisCursos.isEnabled()){
            visualizarVentanas(false,false,false,false,false,false,true,false,false,false);
            cambiarVentanas(7);
        }
    }//GEN-LAST:event_menuMisCursosMouseClicked

    private void menuDiplomasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDiplomasMouseClicked
        if(menuDiplomas.isEnabled()){
            visualizarVentanas(false,false,false,false,false,false,false,true,false,false);
            cambiarVentanas(8);
        }
    }//GEN-LAST:event_menuDiplomasMouseClicked

    private void menuCuestionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCuestionariosMouseClicked
        if(menuCuestionarios.isEnabled()){
            visualizarVentanas(false,false,false,false,false,false,false,false,true,false);
            cambiarVentanas(9);
        }
    }//GEN-LAST:event_menuCuestionariosMouseClicked

    private void menuFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFacturasMouseClicked
        if(menuFacturas.isEnabled()){
            visualizarVentanas(false,false,false,false,false,false,false,false,false,true);
            cambiarVentanas(10);
        }
    }//GEN-LAST:event_menuFacturasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jmMenus;
    private javax.swing.JMenu menuCuestionarios;
    private javax.swing.JMenu menuCursos;
    private javax.swing.JMenu menuDiplomas;
    private javax.swing.JMenu menuFacturas;
    private javax.swing.JMenu menuIngreso;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuMisCursos;
    private javax.swing.JMenu menuRegistro;
    // End of variables declaration//GEN-END:variables

    public void habilitar(boolean ini,boolean ing,boolean reg,
                          boolean mcur,boolean dip,boolean cues,
                          boolean fac)
    {
        menuInicio.setEnabled(ini);
        menuIngreso.setEnabled(ing);
        menuRegistro.setEnabled(reg);        
        menuMisCursos.setEnabled(mcur);
        menuDiplomas.setEnabled(dip);
        menuCuestionarios.setEnabled(cues);
        menuFacturas.setEnabled(fac);
    }
    
    public void visualizarVentanas(boolean ini,boolean ing,boolean reg,
                                   boolean cur,boolean est,boolean adm,
                                   boolean misc,boolean dip,boolean cue,
                                   boolean fact)
    {
        inicio.setVisible(ini);
        ingreso.setVisible(ing);
        registro.setVisible(reg);
        cursos.setVisible(cur);
        estu.setVisible(est);
        admin.setVisible(adm);
        cursosp.setVisible(misc);  
        diplomas.setVisible(dip);
        cues.setVisible(cue);        
        fac.setVisible(fact);
    }
    
    public void cambiarVentanas(int v){
        switch(v){
            case 1->{
                inicio.setSize(1000,700);
                inicio.mostrarCrusos();
                this.setContentPane(inicio);
            }
            case 2->{
                ingreso.setSize(this.getSize());
                this.setContentPane(ingreso);
            }
            case 3-> {
                registro.setSize(this.getSize());
                this.setContentPane(registro);
            }
            case 4->{         
                estu.cargarDatos();
                estu.setSize(this.getSize());
                this.setContentPane(estu);                
            }
            case 5->{
                admin.setSize(this.getSize());
                this.setContentPane(admin);
            }
            case 6->{
                cursos.cargarCursos();
                cursos.setSize(this.getSize());
                this.setContentPane(cursos);            
            }
            case 7->{
                cursosp.cargarCursos();
                cursosp.setSize(this.getSize());
                this.setContentPane(cursosp);
            }
            case 8->{
                diplomas.cargarDiplomas();
                diplomas.setSize(this.getSize());
                this.setContentPane(diplomas);                
            }
            case 9->{
                cues.cargarTabla();
                cues.setSize(this.getSize());
                this.setContentPane(cues);
            }
            case 10->{
                fac.setSize(this.getSize());
                this.setContentPane(fac);
                fac.info();
            }
        }        
    }
    
}
