/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.UsuarioCtrl;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author juans
 */
public class Registro extends javax.swing.JPanel {
    private final UsuarioCtrl usuCt;
    /**
     * @param usuCt
     */
    public Registro(UsuarioCtrl usuCt) {
        this.usuCt=usuCt;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        psContraseña = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ablaze academy.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(766, 0, 234, 196);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Edad:");
        add(jLabel4);
        jLabel4.setBounds(340, 450, 62, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Contraseña:");
        add(jLabel2);
        jLabel2.setBounds(340, 290, 126, 29);

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verificar.png"))); // NOI18N
        btnRegistro.setToolTipText("Registrar");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        add(btnRegistro);
        btnRegistro.setBounds(460, 540, 65, 41);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Registro");
        add(jLabel6);
        jLabel6.setBounds(440, 100, 87, 29);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Nombre completo:");
        add(jLabel1);
        jLabel1.setBounds(340, 370, 190, 29);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Cédula:");
        add(jLabel3);
        jLabel3.setBounds(340, 210, 81, 29);

        txtCedula.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtCedula);
        txtCedula.setBounds(340, 240, 320, 27);

        txtEdad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtEdad);
        txtEdad.setBounds(340, 480, 320, 27);

        txtNombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtNombre);
        txtNombre.setBounds(340, 400, 320, 27);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ablaze academy.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 234, 196);
        add(psContraseña);
        psContraseña.setBounds(340, 320, 320, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        registro();
    }//GEN-LAST:event_btnRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField psContraseña;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void registro() {
        try{            
        Usuario usu=new Usuario(String.valueOf(psContraseña.getPassword()),
                                txtNombre.getText(),
                                1,
                                Integer.parseInt(txtCedula.getText()),
                                Integer.parseInt(txtEdad.getText()));
        limpiarCampos();
        if(usuCt.registrar(usu)){
            JOptionPane.showMessageDialog(this,"Registrado","Confirmacion",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"No se pudo realizar el registro","Alerta",JOptionPane.ERROR_MESSAGE);
        }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Revisa que los datos sean correctos","Alerta",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiarCampos(){
        txtCedula.setText("");
        psContraseña.setText("");
        txtEdad.setText("");
        txtNombre.setText("");
    }
}
